spring.cloud.stream.bindings.process-in-0.destination: words-1
spring.cloud.stream.bindings.process-out-0.destination: counts-1
spring.cloud.stream.kafka.streams.binder.application-id: kstream-metics-appplication-id-1

spring.cloud.stream.kafka.streams.binder:
  configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    commit.interval.ms: 1000
    metrics:
      recording:
        level: DEBUG

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: metrics,health,bindings,kafkastreamstopology